name: Test and Report

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Run tests and create report
        run: |
          mvn clean test
          ./allure/bin/allure generate target/allure-results --clean -o target/allure-report

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: allure-report
          path: target/allure-report
          
      - name: Publish to Allure Server
        run: |
          curl -X POST "https://your-allure-server/api/report" \
               -H "Content-Type: multipart/form-data" \
               -F "file=@target/allure-report.zip"
